### ISSUE TITLE
Putty 0.67 Windows Pageant doesn't have Add CAPI Cert

### ISSUE THREAD

**Issue by giesberge** [risacher/putty-cac#24]
@jdantzler Just started up the windows executable version of pageant and there's only the Add Key and Remove Key buttons. Add CAPI Cert is not there

**Comment by jdantzler** [comment]
Try the latest one now please.  It should be fixed.  Thanks.

**Comment by giesberge** [comment]
Fixed, thank you

**Comment by rteske2work** [comment]
CAPI cert button missing again in v 0.80

**Comment by rteske2work** [comment]
In v0.81 Add CAPI Cert button still missing.
Is there an update?
